### PR TITLE
Page Editings

### PR DESCRIPTION
**Pull request by Nagle-Keianna**
Linked all the pages together and they all display a navbar now. Also changed the background color of the donation form page to fit the picture more.

### CODE REVIEW

**Review by AlexandreMig — CHANGES_REQUESTED** [review]
There are two of each item page. One set is empty and the other has the basic code to it. You added the nav bar to the pages that don't have any code in it. Besides that, everything looks good!

**Comment by Nagle-Keianna** [comment]
I'm unsure what you mean by two of each item page. Are you talking about the difference between the src folder and the target folder? I know the target folders should have no code in them. I added the nav bar to pages that didn't have any code in them because when ran those pages were blank.

**Comment by AlexandreMig** [comment]
> I'm unsure what you mean by two of each item page. Are you talking about the difference between the src folder and the target folder? I know the target folders should have no code in them. I added the nav bar to pages that didn't have any code in them because when ran those pages were blank.

I mean that, there are item_pages/food.html and Food.html. Two sets of pages for the items. But only one of them have code in it

**Comment by Nagle-Keianna** [comment]
> > I'm unsure what you mean by two of each item page. Are you talking about the difference between the src folder and the target folder? I know the target folders should have no code in them. I added the nav bar to pages that didn't have any code in them because when ran those pages were blank.
> 
> I mean that, there are item_pages/food.html and Food.html. Two sets of pages for the items. But only one of them have code in it

Okay I see what I did. I didn't pull before I made changes so I didn't see that you had created HTML files for those pages. That's why I had made those pages in addition. I'm gonna just add the nav bar to the ones you created my bad.

**Pull request closed without merging**
